Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  #config.vm.network "private_network", 
  #                  ip: "192.168.10.50"
  config.vm.network "public_network",
                    bridge: "Realtek Gaming 2.5GbE Family Controller"
  
  #config.vm.network "forwarded_port", guest: 8000, host: 8000
  #config.vm.network "forwarded_port", guest: 22, host: 2222

  config.vm.provider "virtualbox" do |vb|
    #vb.gui = true
    vb.memory = 4096
    vb.cpus = 2
  end
end
