Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.network "forwarded_port", guest: 8000, host: 8000

  # Используем внешний bash-скрипт
  config.vm.provision "shell", path: "provision.sh"
end
