Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.network "public_network",
                    bridge: "Realtek Gaming 2.5GbE Family Controller"
  
  config.vm.provider "virtualbox" do |vb|
    #vb.gui = true
    vb.memory = 4096
    vb.cpus = 2
  end
end
